CREATE SCHEMA IF NOT EXISTS gaming;

CREATE TABLE gaming.games (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    name TEXT,
    first_release_date BIGINT
);

CREATE TABLE gaming.genres (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    name TEXT,
    slug TEXT,
    url TEXT
);

CREATE TABLE gaming.platform_categories (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    name TEXT
);

CREATE TABLE gaming.platforms (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    name TEXT,
    slug TEXT,
    id_platform_category SMALLINT REFERENCES gaming.platform_categories(id),
    logo_url TEXT,
    url TEXT,
    alternative_name TEXT,
    logo_id SMALLINT
);

CREATE TABLE gaming.games_genres (
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    id_game INTEGER NOT NULL REFERENCES gaming.games(id),
    id_genre SMALLINT NOT NULL REFERENCES gaming.genres(id),
    PRIMARY KEY (id_game, id_genre)
);

CREATE TABLE gaming.games_platforms (
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    id_game INTEGER NOT NULL REFERENCES gaming.games(id),
    id_platform SMALLINT NOT NULL REFERENCES gaming.platforms(id),
    PRIMARY KEY (id_game, id_platform)
);