CREATE SCHEMA IF NOT EXISTS gaming;

CREATE TABLE gaming.games (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    name TEXT,
    first_release_date BIGINT
);

CREATE TABLE gaming.genres (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    name TEXT,
    slug TEXT,
    url TEXT
);

CREATE TABLE gaming.platform_categories (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    name TEXT
);

CREATE TABLE gaming.platforms (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    name TEXT,
    slug TEXT,
    category SMALLINT REFERENCES gaming.platform_categories(id),
    logo_url TEXT,
    url TEXT,
    alternative_name TEXT,
    logo_id SMALLINT
);

CREATE TABLE gaming.games_genres (
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    game_id INTEGER NOT NULL REFERENCES gaming.games(id),
    genre_id SMALLINT NOT NULL REFERENCES gaming.genres(id),
    PRIMARY KEY (game_id, genre_id)
);

CREATE TABLE gaming.games_platforms (
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    game_id INTEGER NOT NULL REFERENCES gaming.games(id),
    platform_id SMALLINT NOT NULL REFERENCES gaming.platforms(id),
    PRIMARY KEY (game_id, platform_id)
);